<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title><?=$this->title; ?></title>
	<?=$this->css('default', 'screen', false); ?>
</head>
<body>
	<h1><?=$this->image('artisan_system_logo.png', 'Artisan System Framework'); ?></h1>
	<?=$this->__content; ?>
</body>
</html>